### ISSUE TITLE
Follow-mode seem to elevates CPU usage

### ISSUE THREAD

**Issue by edumerco** [Lindydancer/multicolumn#3] opened 2017-08-31 12:06 UTC
Hello Anders. 

I just found that when follow-mode is on, it elevates emacs CPU usage to from less than 1% to 99%, as reported by htop. I tried a few times alternating between on and off, and each time happens the same. 

I have here: 
+ GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) in Debian 8.9
+ Org mode version 9.0.9 (9.0.9-88-g251f88-elpa)

What more information could be useful? I would love to help to pinpoint what's happening. 
BTW, thanks a lot for your wonderful mode. :)

Best...

**Comment by Lindydancer** [comment] 2017-08-31 12:55
Hi!

Strange, I haven't seen that here (although I mostly use Emacs on mac or
windows). Do you run in a terminal or a GUI?

Can you reproduce it from "emacs -Q" (i.e. without any init files)?

One thing that could affect follow-mode is the window layout. In
particular, it prefers when the windows have exactly the same width, and
when there are no partial lines at the bottom of the windows.

    -- Anders

On Thu, Aug 31, 2017 at 2:06 PM, Eduardo Mercovich <notifications@github.com

**Comment by edumerco** [comment] 2017-08-31 14:46
Hi Anders.

>> I just found that when follow-mode is on, it elevates emacs CPU 
>> usage to from less than 1% to 99%, as reported by htop. I tried 
>> a few times alternating between on and off, and each time 
>> happens the same.
[...]

> Strange, I haven't seen that here (although I mostly use Emacs 
> on mac or windows). Do you run in a terminal or a GUI?

GUI (openbox on Debian).

> Can you reproduce it from "emacs -Q" (i.e. without any init 
> files)?

Tried it and it doesn't. So it seems it may be some other thing in 
my config... 

> One thing that could affect follow-mode is the window layout. In 
> particular, it prefers when the windows have exactly the same 
> width, and when there are no partial lines at the bottom of the 
> windows.

The split was just done, so they are equals in width. Partial 
lines no, at least when I did this test. 

However, trying again I did it different and saw something 
interesting. Usually I split and then enable follow-mode.
This time however...
1. I enabled follow-mode and no higher CPU usage was observed.
2. Then splitted the window and in that instant, CPU usage goes 
up.

However, since it doesn't happen with emacs -Q it must be some 
other thing, which of course I'll search. 

Sorry for bothering you. Now that I know the option to start 
without configuration I'll always do it 1st. :)

Do you close the issue, or do I do it?

Thanks a lot... :)


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by Lindydancer** [comment] 2017-08-31 16:05
Hi!

Follow-mode doesn't do anything much when there is only one window. In
other words, if the CPU usage goes up when you run "emacs -Q", enable
follow-mode, and split the windows there is definitively a problem with
follow-mode. (Your letter wasn't 100% clear if this was the case.)

One thing you could test is to do the same on a newer Emacs version (the
latest released is 25.2).

When it comes to closing the issue, you can surely do that, as it is
reported on the "multicolumn" package. I'm the author of both multicolumn
and follow-mode (although I wrote them 20 years apart). However,
follow-mode has been part of the Emacs distribution for many years and bugs
on it should be reported as a normal Emacs bug.


If this is caused by something in your init file, you can try to start
Emacs with the first half of it. If the problem is seen, then it must be in
the first half, otherwise in the second. You can repeat this with the first
quarter etc. until you have isolated the problem. If you find the cause of
the problem, please let me know what it is!

    -- Anders

On Thu, Aug 31, 2017 at 4:46 PM, Eduardo Mercovich <notifications@github.com

**Comment by edumerco** [comment] 2017-09-05 01:38
Hi Anders.

> Follow-mode doesn't do anything much when there is only one 
> window. In other words, if the CPU usage goes up when you run 
> "emacs -Q", enable follow-mode, and split the windows there is 
> definitively a problem with follow-mode. [...]

I checked again but couldn't reproduce the problem. I'm sure it 
was like I reported previously but it may have been something in 
that session. 

> When it comes to closing the issue, you can surely do that, as 
> it is reported on the "multicolumn" package. I'm the author of 
> both multicolumn and follow-mode (although I wrote them 20 years 
> apart).

Sorry, now I see I reported it on the wrong package... <:)

> [...] If you find the cause of the problem, please let me know 
> what it is!

I will try again but for the moment I would close it, since I 
can't reproduce that again.

Sorry to bother.

And thanks a lot for your wonderful follow-mode. :)

Best regards...


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Closed as completed** 2017-09-05 01:39 UTC

**Comment by Lindydancer** [comment] 2017-09-05 07:07
Hi!


> > When it comes to closing the issue, you can surely do that, as
> > it is reported on the "multicolumn" package. I'm the author of
> > both multicolumn and follow-mode (although I wrote them 20 years
> > apart).
>
> Sorry, now I see I reported it on the wrong package... <:)
>

Well, it ended up at the right person in the end, that's what important.


> [...] If you find the cause of the problem, please let me know
> > what it is!
>
> I will try again but for the moment I would close it, since I
> can't reproduce that again.
>
> Sorry to bother.
>

It wasn't a bother!

I hear very little about follow-mode these days -- I'm always glad to hear
when I do, so that I know that it isn't forgotten.


And thanks a lot for your wonderful follow-mode. :)
>

Thank you very much!

    -- Anders
